#!/usr/bin/env bash
# Regenerates include/UpdateRootCAs.h from the macOS system trust store.
#
# The device pins these two roots for its update channel instead of trusting
# every CA on the internet:
#
#   USERTrust ECC Certification Authority  -> github.com          (expires 2038-01-18)
#   ISRG Root X1                           -> *.githubusercontent.com (expires 2035-06-04)
#
# github.com serves a Sectigo chain cross-signed by USERTrust ECC, and the
# release-asset redirect lands on objects.githubusercontent.com, which serves a
# Let's Encrypt chain anchored at ISRG Root X1. Both links are needed.
#
# If GitHub ever changes issuers, update checks start failing with a TLS error
# in the serial log. Re-run this script to re-pin. Verify what is actually
# served first:
#   openssl s_client -connect github.com:443 -servername github.com </dev/null 2>/dev/null | grep 'i:'
set -euo pipefail

KEYCHAIN=/System/Library/Keychains/SystemRootCertificates.keychain
OUT="$(dirname "$0")/../include/UpdateRootCAs.h"

emit_cert() {
    security find-certificate -a -c "$1" -p "$KEYCHAIN" \
        | awk '/BEGIN CERT/{p=1} p{print} /END CERT/{if(p){exit}}' \
        | sed 's/^/"/; s/$/\\n"/'
}

{
    echo '#pragma once'
    echo
    echo '// GENERATED by scripts/generate_ca_header.sh -- do not edit by hand.'
    echo '//'
    echo '// Trust anchors for the firmware update channel. Pinning these two roots'
    echo '// means a machine on the network path cannot serve the radar a forged'
    echo '// manifest or a forged firmware image.'
    echo '//'
    echo '//   USERTrust ECC Certification Authority -> github.com'
    echo '//   ISRG Root X1                          -> *.githubusercontent.com'
    echo '//'
    echo '// mbedtls accepts several concatenated PEM certificates in one buffer and'
    echo '// treats each as a trust anchor, so both live in a single string.'
    echo
    echo 'namespace UpdateRootCAs {'
    echo
    echo 'inline constexpr char GitHubRoots[] ='
    echo '    // USERTrust ECC Certification Authority -- expires 2038-01-18'
    emit_cert "USERTrust ECC Certification Authority"
    echo '    // ISRG Root X1 -- expires 2035-06-04'
    emit_cert "ISRG Root X1"
    echo '    ;'
    echo
    echo '}  // namespace UpdateRootCAs'
} > "$OUT"

echo "wrote $OUT"
