#!/usr/bin/env python3
"""Regenerate the checked-in QR codes: include/QrCode.h and include/WifiQrCode.h.

Each code is stored as its module grid, one bit per module, rather than as
pixels: a QR is drawn by filling squares, and the size of those squares depends
on the panel rather than on the code. QrBadge in src/ui/QrBadge.cpp picks the
scale and does the filling; ConfigQr and WifiSetupQr each own the grid for one
code and check it against the string it is supposed to encode.

Requires segno. Run from the repo root:

    python3 scripts/generate_qr_code.py
"""

import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import segno
except ImportError:
    sys.exit("missing segno -- pip install segno")

ROOT = Path(__file__).resolve().parent.parent

# The error correction level to ask for, and the floor rather than the answer:
# segno raises it for free whenever a stronger one fits the same version, which
# for a string this short means the M asked for here arrives as Q.
#
# Level matters less than size on a lit panel -- nothing rains on it, and the
# only thing that stops a code being read is modules too small to focus on --
# so the level is only ever allowed to go up where it is free.
ERROR = "m"

# Four modules of clear space on every side, which is what the specification
# asks for and what a phone's decoder looks for before it will believe it has
# found a finder pattern. Drawn by QrBadge rather than baked into the grid
# here, so the grid stays the code itself.
QUIET_ZONE = 4

BYTES_PER_LINE = 12

# Characters the WIFI: URI format reserves for its own syntax. An SSID
# containing one has to be backslash-escaped before it goes in the payload,
# which this script does not do -- so it fails loudly instead of emitting a
# code that looks fine and joins the wrong network.
WIFI_URI_RESERVED = set('\\;,":')


def read(source, pattern):
    match = re.search(pattern, (ROOT / source).read_text())
    if not match:
        sys.exit(f"could not find {pattern!r} in {source}")
    return match.group(1)


def config_address():
    # The address is read out of the firmware rather than written down again
    # here. A badge pointing somewhere the radar does not answer is not
    # something anyone would catch by looking at it -- it is a picture of a
    # mistake -- so there is one spelling of the name and this is not where it
    # lives.
    address = read("src/ConfigurationWebServer.h", r'MdnsAddress\s*=\s*"([^"]+)"')
    return f"http://{address}"


def wifi_join_payload():
    ssid = read("src/WiFiConnection.h", r'SetupHotspotName\s*=\s*"([^"]+)"')
    bad = WIFI_URI_RESERVED & set(ssid)
    if bad:
        sys.exit(f"SetupHotspotName {ssid!r} contains {sorted(bad)}, which the "
                  "WIFI: QR format reserves -- escape it in wifi_join_payload() "
                  "before regenerating")
    # T:nopass -- the setup hotspot is opened with WiFi.softAP(name) and no
    # password, so there is nothing for a decoder to prompt for.
    return f"WIFI:T:nopass;S:{ssid};;"


@dataclass
class Target:
    dest: str            # relative to ROOT
    namespace: str
    symbol: str           # the name of the constexpr char* holding the payload
    payload: str
    doc_what: str         # what the symbol comment says the code is for
    doc_source: str       # where the payload came from, and what regenerates it


def pack(matrix):
    """One bit per module, MSB first, each row padded out to a whole byte."""
    size = len(matrix)
    stride = (size + 7) // 8
    rows = []
    for row in matrix:
        packed = bytearray(stride)
        for x, module in enumerate(row):
            if module:
                packed[x // 8] |= 0x80 >> (x % 8)
        rows.append(packed)
    return stride, rows


def emit(target, version, error, size, stride, rows):
    out = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <cstdint>",
        "",
        "// Generated by scripts/generate_qr_code.py. Do not edit by hand.",
        "//",
        f"// {target.payload}",
        f"// version {version}, error correction {error}, {size}x{size} modules.",
        "//",
        f"// {target.doc_source}",
        f"namespace {target.namespace} {{",
        "",
        f"// {target.doc_what}",
        f'constexpr const char* {target.symbol} = "{target.payload}";',
        "",
        "// Modules per side, without the quiet zone.",
        f"constexpr int Size = {size};",
        "",
        "// Clear modules the code needs around it before a decoder will find it.",
        f"constexpr int QuietZone = {QUIET_ZONE};",
        "",
        "// Bytes per row of Modules; the last one is only partly used.",
        f"constexpr int Stride = {stride};",
        "",
        "// One bit per module, MSB first, dark set.",
        "static const uint8_t Modules[] PROGMEM = {",
    ]

    flat = [f"0x{b:02X}" for row in rows for b in row]
    for j in range(0, len(flat), BYTES_PER_LINE):
        out.append("  " + ", ".join(flat[j:j + BYTES_PER_LINE]) + ",")
    out.append("};")

    out += ["", f"}}  // namespace {target.namespace}", ""]
    return "\n".join(out)


def generate(target):
    code = segno.make(target.payload, error=ERROR, micro=False)
    matrix = [list(row) for row in code.matrix]
    size = len(matrix)
    stride, rows = pack(matrix)

    print(f"{target.payload}")
    print(f"  version {code.version}, error correction {code.error}, "
          f"{size}x{size} modules, {size * stride} bytes")

    dest = ROOT / target.dest
    dest.write_text(emit(target, code.version, code.error, size, stride, rows))
    print(f"wrote {dest.relative_to(ROOT)}")


def main():
    targets = [
        Target(
            dest="include/QrCode.h",
            namespace="QrCode",
            symbol="Url",
            payload=config_address(),
            doc_what="What the code says. Checked against MdnsAddress at compile time --\n"
                     "// see the static_assert in src/ui/ConfigQr.cpp.",
            doc_source="The address comes from MdnsAddress in src/ConfigurationWebServer.h.\n"
                       "// Change that name and this file has to be regenerated with it.",
        ),
        Target(
            dest="include/WifiQrCode.h",
            namespace="WifiQrCode",
            symbol="Payload",
            payload=wifi_join_payload(),
            doc_what="What the code offers to join. Checked against SetupHotspotName at\n"
                     "// compile time -- see the static_assert in src/ui/WifiSetupQr.cpp.",
            doc_source="The name comes from SetupHotspotName in src/WiFiConnection.h.\n"
                       "// Change that name and this file has to be regenerated with it.",
        ),
    ]
    for target in targets:
        generate(target)


if __name__ == "__main__":
    main()
