#!/usr/bin/env python3
"""Regenerate include/QrCode.h -- the QR code for the radar's own address.

The code is stored as its module grid, one bit per module, rather than as
pixels: a QR is drawn by filling squares, and the size of those squares depends
on the panel rather than on the code. ConfigQr in src/ui/ConfigQr.cpp picks the
scale and does the filling.

Requires segno. Run from the repo root:

    python3 scripts/generate_qr_code.py
"""

import re
import sys
from pathlib import Path

try:
    import segno
except ImportError:
    sys.exit("missing segno -- pip install segno")

ROOT = Path(__file__).resolve().parent.parent
DST = ROOT / "include" / "QrCode.h"

# The address is read out of the firmware rather than written down again here.
# A badge pointing somewhere the radar does not answer is not something anyone
# would catch by looking at it -- it is a picture of a mistake -- so there is
# one spelling of the name and this is not where it lives.
MDNS_SOURCE = ROOT / "src" / "ConfigurationWebServer.h"


def address():
    match = re.search(r'MdnsAddress\s*=\s*"([^"]+)"', MDNS_SOURCE.read_text())
    if not match:
        sys.exit(f"could not find MdnsAddress in {MDNS_SOURCE}")
    return f"http://{match.group(1)}"


# The error correction level to ask for, and the floor rather than the answer:
# segno raises it for free whenever a stronger one fits the same version, which
# for an address this short means the M asked for here arrives as Q.
#
# Level matters less than size on a lit panel -- nothing rains on it, and the
# only thing that stops a code being read is modules too small to focus on --
# so the level is only ever allowed to go up where it is free.
ERROR = "m"

# Four modules of clear space on every side, which is what the specification
# asks for and what a phone's decoder looks for before it will believe it has
# found a finder pattern. Drawn by ConfigQr rather than baked into the grid
# here, so the grid stays the code itself.
QUIET_ZONE = 4

BYTES_PER_LINE = 12


def pack(matrix):
    """One bit per module, MSB first, each row padded out to a whole byte."""
    size = len(matrix)
    stride = (size + 7) // 8
    rows = []
    for row in matrix:
        packed = bytearray(stride)
        for x, module in enumerate(row):
            if module:
                packed[x // 8] |= 0x80 >> (x % 8)
        rows.append(packed)
    return stride, rows


def emit(url, version, error, size, stride, rows):
    out = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <cstdint>",
        "",
        "// Generated by scripts/generate_qr_code.py. Do not edit by hand.",
        "//",
        f"// {url}",
        f"// version {version}, error correction {error}, {size}x{size} modules.",
        "//",
        "// The address comes from MdnsAddress in src/ConfigurationWebServer.h.",
        "// Change that name and this file has to be regenerated with it.",
        "namespace QrCode {",
        "",
        "// What the code says. Checked against MdnsAddress at compile time --",
        "// see the static_assert in src/ui/ConfigQr.cpp.",
        f'constexpr const char* Url = "{url}";',
        "",
        "// Modules per side, without the quiet zone.",
        f"constexpr int Size = {size};",
        "",
        "// Clear modules the code needs around it before a decoder will find it.",
        f"constexpr int QuietZone = {QUIET_ZONE};",
        "",
        "// Bytes per row of Modules; the last one is only partly used.",
        f"constexpr int Stride = {stride};",
        "",
        "// One bit per module, MSB first, dark set.",
        "static const uint8_t Modules[] PROGMEM = {",
    ]

    flat = [f"0x{b:02X}" for row in rows for b in row]
    for j in range(0, len(flat), BYTES_PER_LINE):
        out.append("  " + ", ".join(flat[j:j + BYTES_PER_LINE]) + ",")
    out.append("};")

    out += ["", "}  // namespace QrCode", ""]
    return "\n".join(out)


def main():
    url = address()
    code = segno.make(url, error=ERROR, micro=False)
    matrix = [list(row) for row in code.matrix]
    size = len(matrix)
    stride, rows = pack(matrix)

    print(f"{url}")
    print(f"  version {code.version}, error correction {code.error}, "
          f"{size}x{size} modules, {size * stride} bytes")

    DST.write_text(emit(url, code.version, code.error, size, stride, rows))
    print(f"wrote {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
