#!/usr/bin/env python3
"""Regenerate include/QrCode.h -- the QR code for the project's GitHub page.

The code is stored as its module grid, one bit per module, rather than as
pixels: a QR is drawn by filling squares, and the size of those squares depends
on the panel rather than on the code. ProjectQr in src/ui/ProjectQr.cpp picks
the scale and does the filling.

Requires segno. Run from the repo root:

    python3 scripts/generate_qr_code.py
"""

import sys
from pathlib import Path

try:
    import segno
except ImportError:
    sys.exit("missing segno -- pip install segno")

ROOT = Path(__file__).resolve().parent.parent
DST = ROOT / "include" / "QrCode.h"

URL = "https://github.com/thedontknowguy/micro-radar"

# What actually goes in the code, and the reason the badge on the address screen
# is readable at all.
#
# QR has a mode for uppercase letters, digits and a handful of punctuation that
# spends 5.5 bits a character where the general one spends 8. This URL in mixed
# case is 45 bytes and needs a version 4 symbol, 33 modules across; in upper
# case it is 45 alphanumeric characters and fits a version 2, 25 across. On a
# panel where the badge gets a hundred pixels either way, that is the difference
# between three pixels a module and two -- and two is what a phone camera fails
# to focus on.
#
# Safe because neither half of the address cares: hostnames are case-insensitive
# by definition, and GitHub answers an upper-case owner and repository directly
# rather than by redirect. The scheme, which is what tells a scanner this is a
# link worth offering to open, is case-insensitive too.
ENCODED = URL.upper()

# The error correction level to ask for. Low, and deliberately: the levels above
# it are there for codes that get printed, handled and rained on, and they buy
# that robustness with more modules -- Q would push this back to a version 3 and
# two-pixel modules. A code on a lit panel is never damaged; the only thing that
# stops it being read is being too small.
ERROR = "l"

# Four modules of clear space on every side, which is what the specification
# asks for and what a phone's decoder looks for before it will believe it has
# found a finder pattern. Drawn by QrScreen rather than baked into the grid
# here, so the grid stays the code itself.
QUIET_ZONE = 4

BYTES_PER_LINE = 12


def pack(matrix):
    """One bit per module, MSB first, each row padded out to a whole byte."""
    size = len(matrix)
    stride = (size + 7) // 8
    rows = []
    for row in matrix:
        packed = bytearray(stride)
        for x, module in enumerate(row):
            if module:
                packed[x // 8] |= 0x80 >> (x % 8)
        rows.append(packed)
    return stride, rows


def emit(encoded, version, error, size, stride, rows):
    out = [
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "#include <cstdint>",
        "",
        "// Generated by scripts/generate_qr_code.py. Do not edit by hand.",
        "//",
        f"// {encoded}",
        f"// version {version}, error correction {error}, {size}x{size} modules.",
        "//",
        "// Upper case to halve the symbol -- see the generator for why that is",
        "// safe, and what it is worth on a panel this size.",
        "namespace QrCode {",
        "",
        "// What the code says, for the log line that goes out with it.",
        f'constexpr const char* Url = "{encoded}";',
        "",
        "// Modules per side, without the quiet zone.",
        f"constexpr int Size = {size};",
        "",
        "// Clear modules the code needs around it before a decoder will find it.",
        f"constexpr int QuietZone = {QUIET_ZONE};",
        "",
        "// Bytes per row of Modules; the last one is only partly used.",
        f"constexpr int Stride = {stride};",
        "",
        "// One bit per module, MSB first, dark set.",
        "static const uint8_t Modules[] PROGMEM = {",
    ]

    flat = [f"0x{b:02X}" for row in rows for b in row]
    for j in range(0, len(flat), BYTES_PER_LINE):
        out.append("  " + ", ".join(flat[j:j + BYTES_PER_LINE]) + ",")
    out.append("};")

    out += ["", "}  // namespace QrCode", ""]
    return "\n".join(out)


def main():
    # A guard on the one thing that could quietly turn the address into a
    # different one: the upper-casing above is only safe while it changes case
    # and nothing else.
    if ENCODED.lower() != URL.lower():
        sys.exit("ENCODED is not URL in another case")

    code = segno.make(ENCODED, error=ERROR, micro=False)
    matrix = [list(row) for row in code.matrix]
    size = len(matrix)
    stride, rows = pack(matrix)

    print(f"{ENCODED}")
    print(f"  version {code.version}, error correction {code.error}, "
          f"{size}x{size} modules, {size * stride} bytes")

    DST.write_text(emit(ENCODED, code.version, code.error, size, stride, rows))
    print(f"wrote {DST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
